// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-G97z6tqdj3DRRWvAR2CYSEn8K_e51wI',
    appId: '1:164141713711:web:d75efc647ea07e55b339da',
    messagingSenderId: '164141713711',
    projectId: 'fit-pa',
    authDomain: 'fit-pa.firebaseapp.com',
    storageBucket: 'fit-pa.appspot.com',
    measurementId: 'G-7TXLXTR3W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ND3uC0OKUIJwkjENfeich_ZHWjBkfZI',
    appId: '1:164141713711:android:d640636edd82eb0ab339da',
    messagingSenderId: '164141713711',
    projectId: 'fit-pa',
    storageBucket: 'fit-pa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuBjDBwhP4XTB_lwv1ZTcrS_3dgeOB7UE',
    appId: '1:164141713711:ios:17998c8c2bbe6142b339da',
    messagingSenderId: '164141713711',
    projectId: 'fit-pa',
    storageBucket: 'fit-pa.appspot.com',
    iosClientId: '164141713711-rrcmtaabktl910roja4vlqcd1n75ulks.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitPalette2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuBjDBwhP4XTB_lwv1ZTcrS_3dgeOB7UE',
    appId: '1:164141713711:ios:49400b0da65268a4b339da',
    messagingSenderId: '164141713711',
    projectId: 'fit-pa',
    storageBucket: 'fit-pa.appspot.com',
    iosClientId: '164141713711-mhqfr8h76pgpdcu8b8iuts9fiu6081jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitPalette2.RunnerTests',
  );
}
